# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Allow manual runs and run on push to main/master
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit the generated SVG
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token with necessary scopes
          token: ${{ secrets.METRICS_TOKEN }}

          # Output settings
          output_action: commit
          output: github-metrics.svg

          # Basic settings
          user: BloodhavenStudios
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome

          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          # Code plugin
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 30
          plugin_code_load: 400
          plugin_code_visibility: public

          # Languages plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Notable contributions plugin
          plugin_notable: yes
          plugin_notable_filter: stars:>20
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit
